### ISSUE TITLE
Api Augment npm release should not set RC releases as latest

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/frequency#1776]
When publishing an RC release, CI npm publishing tags the rc release as `latest` when it should only tag it with the version.

Solution: Remove the latest tag push from CI for RC releases, but maintain the version publishing.

See `.github/workflows/release.yml`

```yaml
- name: Release on NPM @latest
   if: env.TEST_RUN != 'true'
   run: npm publish --tag latest --access public
```

Helpful: `if: steps.is-full-release.outputs.is-full-release != 'true'`
