### ISSUE TITLE
Investigate Compiling after Restoring Dependencies in Verify PR CI workflow

### ISSUE THREAD

**Issue by demisx** [LibertyDSNP/frequency#575]
Thank you @shannonwells for pointing this out as a valid concern. Currently, when Verify PR workflow run on each PR commit we are [caching rust dependencies here](https://github.com/LibertyDSNP/frequency/blob/d5fe2c42eafcf925e1569ed0b333b81d9821e104/.github/workflows/verify-pr-commit.yml#L52-L55) (not frequency code, only the dependent crates) during build time:

```yml
      - name: Save/Restore Dependencies from Cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{env.RUST_TOOLCHAIN}}
     ...
      - name: Compile for Mainnet
        run: |
          CARGO_INCREMENTAL=0 RUSTFLAGS="-D warnings" cargo build --locked --release \
            --features  frequency
```

The dependencies are then [successfully restored from cache here](https://github.com/LibertyDSNP/frequency/blob/d5fe2c42eafcf925e1569ed0b333b81d9821e104/.github/workflows/verify-pr-commit.yml#L189-L192) before running cargo test:

```yml
      - name: Restore Dependencies from Cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{env.RUST_TOOLCHAIN}}
      - name: Run Tests
        run: cargo test --all-features --workspace --release
```

However, even when dependencies are restored successfully, the `cargo test` command above still does a bunch of [compiling like this](https://github.com/LibertyDSNP/frequency/actions/runs/3322507466/jobs/5491632810) and takes awfully long time - over 1.5 hrs:

```
   Compiling proc-macro2 v1.0.47
   Compiling quote v1.0.21
   Compiling unicode-ident v1.0.5
   Compiling syn v1.0.[10](https://github.com/LibertyDSNP/frequency/actions/runs/3322856263/jobs/5492459391#step:5:11)2
   Compiling libc v0.2.[13](https://github.com/LibertyDSNP/frequency/actions/runs/3322856263/jobs/5492459391#step:5:14)5
   Compiling version_check v0.9.4
   Compiling autocfg v1.1.0
   Compiling cfg-if v1.0.0
   Compiling serde_derive v1.0.[14](https://github.com/LibertyDSNP/frequency/actions/runs/3322856263/jobs/5492459391#step:5:15)5
   Compiling serde v1.0.145
   Compiling jobserver v0.1.25
   Compiling cc v1.0.73
   Compiling memchr v2.5.0
   Compiling value-bag v1.0.0-alpha.9
   Compiling log v0.4.17
   Compiling ctor v0.1.23
   Compiling thiserror v1.0.37
   Compiling thiserror-impl v1.0.37
   Compiling typenum v1.[15](https://github.com/LibertyDSNP/frequency/actions/runs/3322856263/jobs/5492459391#step:5:16).0
   Compiling generic-array v0.14.6
   Compiling once_cell v1.15.0
   Compiling getrandom v0.2.7
   Compiling ahash v0.7.6
   Compiling toml v0.5.9
   Compiling indexmap v1.9.1
   Compiling anyhow v1.0.65
...
```

I would expect that if dependencies are restored from cache then only our own Frequency code will be compiled. However, I am not a Rust programmer and not sure if compiling all these non-Frequency libraries is justified in this case or not. If not, then I will debug the CI cache action further to see where it goes wrong. Any ideas are welcome.
